version: "3.9"
services:
  garage-api:
    image: liorelb/x-garage-api
    environment:
      GARAGE_MONGO_CONNECTION_STR: "mongodb://mongo:27017"
    ports:
      - "8000:8000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
